### ISSUE TITLE
Budgeting support ?

### ISSUE THREAD

**Issue by mvsrgc** [NickvisionApps/Denaro#761] opened 2023-12-19 22:12 UTC
Denaro has an impressive design and functionality. I'm curious if there are any thoughts on incorporating envelope-style budgeting features? Having a tool like this in the open-source space, especially one that integrates with libadwaita, would be fantastic. Denaro already offers an excellent financial overview, but adding budgeting capabilities could make it even more useful and powerful.

Denaro could be an attractive YNAB alternative, especially for those preferring non-subscription-based (SaaS) financial tools. This addition could carve a niche for Denaro in the open-source budgeting space.

**Comment by nlogozzo** [comment] 2023-12-21 05:56
Duplicate of #367

**Closed by nlogozzo** 2023-12-21 05:56 UTC
