### ISSUE TITLE
Scheduled Transactions

### ISSUE THREAD

**Issue by josiejojo123** [NickvisionApps/Denaro#718] opened 2023-09-22 07:00 UTC
Hi,

I have been trying out Denaro on my Linux Mint install. I really like the look of Denaro and its simplicity, although I have my pension paid to me every 4 weeks as opposed to monthly. Is there a way to do this or is there a possibility to add this feature to Denaro?

Kind regards and a huge amount of thanks for the work you have put into Denaro. Joanne

**Comment by fsobolev** [comment] 2023-09-22 07:12
Hi!
This is currently not possible but we will definitely work on this.
Closing as duplicate of #542

**Closed by fsobolev** 2023-09-22 07:12 UTC
