### ISSUE TITLE
Feature request: differentiate "Today" from no date filter

### ISSUE THREAD

**Issue by cassiogomes00** [NickvisionApps/Denaro#802] opened 2024-04-06 23:32 UTC
There is no way to see only today's transactions. It would be nice if I could see today's transactions and remove the date filter in two separate options.

**Comment by nlogozzo** [comment] 2024-04-07 01:45
Duplicate of #746 

Will be fixed in the new design (#784)

**Closed by nlogozzo** 2024-04-07 01:45 UTC
