### ISSUE TITLE
Flatpak - Can't Open From App Grid

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#530] opened 2023-05-28 13:55 UTC
With V2023.5.0 update, Denaro installed from flatpak seems to not be able to be opened from the app grid.
Snap is unaffected
Workaround: Run from terminal (`flatpak run org.nickvision.money`)

**Comment by JPF3N998** [comment] 2023-05-29 04:32
Can confirm! Thanks for reporting this issue :)

Running Manjaro with GNOME.

Haven't tried Snap but trying to open Denaro from applications menu fails. Both installed via `flatpak in CLI` and `Add/Remove Software`

**Comment by fsobolev** [comment] 2023-05-29 04:40
There was a flatpak update published with temporary fix, another solution will come to the next version so the issue is still opened.

**Comment by JPF3N998** [comment] 2023-05-29 05:38
Thanks for the update Fyodor!

**Comment by fsobolev** [comment] 2023-05-29 18:06
Fixed with #533

**Closed by fsobolev** 2023-05-29 18:06 UTC
Labels: bug

**Comment by nlogozzo** [comment] 2023-06-16 13:05
https://github.com/NickvisionApps/Denaro/releases/tag/2023.6.0
