### ISSUE TITLE
Amount Input field

### ISSUE THREAD

**Issue by n1729m** [NickvisionApps/Denaro#651] opened 2023-08-19 02:31 UTC
**Current behavior:** When Amount input field is selected and amount entered (Ex: 100).
    
![Screenshot_20230819_075436](https://github.com/NickvisionApps/Denaro/assets/96682069/0618ae75-a72f-4fd9-99f3-600e71e84e8a)
 **0.00** has to be manually deleted each time.

**Proposal:** Whenever amount input field is selected and amount entered, then numbers should overwrite **0.00**
![Screenshot_20230819_075357](https://github.com/NickvisionApps/Denaro/assets/96682069/3a9ead4d-fb5a-45fb-a33e-28b3b1e303cb)

**Comment by fsobolev** [comment] 2023-08-19 04:07
Duplicate of #237

**Closed by fsobolev** 2023-08-19 04:07 UTC
